//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BWYResFactory {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BWYResFactory.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 DALServer 的本地化字符串。
        /// </summary>
        internal static string DALServerName {
            get {
                return ResourceManager.GetString("DALServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provider=OraOLEDB.Oracle.1;User ID={0};Password={1};Data Source=(DESCRIPTION = (ADDRESS_LIST= (ADDRESS = (PROTOCOL = TCP)(HOST = {2})(PORT = 1521))) (CONNECT_DATA = (SERVICE_NAME = {3}))) 的本地化字符串。
        /// </summary>
        internal static string ORACLECONN {
            get {
                return ResourceManager.GetString("ORACLECONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataTye{0}{1}{2}ConnectStr{0}{3}{2}ConnectType{0}{4} 的本地化字符串。
        /// </summary>
        internal static string SaveStr {
            get {
                return ResourceManager.GetString("SaveStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string SQLAnd {
            get {
                return ResourceManager.GetString("SQLAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From 的本地化字符串。
        /// </summary>
        internal static string SQLFrom {
            get {
                return ResourceManager.GetString("SQLFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group By 的本地化字符串。
        /// </summary>
        internal static string SQLGroup {
            get {
                return ResourceManager.GetString("SQLGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Join 的本地化字符串。
        /// </summary>
        internal static string SQLLeftJoin {
            get {
                return ResourceManager.GetString("SQLLeftJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        internal static string SQLOn {
            get {
                return ResourceManager.GetString("SQLOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT 的本地化字符串。
        /// </summary>
        internal static string SQLSelect {
            get {
                return ResourceManager.GetString("SQLSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 server={0};database={1};uid={2};password={3} 的本地化字符串。
        /// </summary>
        internal static string SQLSERVERCONN {
            get {
                return ResourceManager.GetString("SQLSERVERCONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Where 的本地化字符串。
        /// </summary>
        internal static string SQLWhere {
            get {
                return ResourceManager.GetString("SQLWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BWYDB_SYS 的本地化字符串。
        /// </summary>
        internal static string SysDBNm {
            get {
                return ResourceManager.GetString("SysDBNm", resourceCulture);
            }
        }
    }
}
